
import { Config } from './types';

export const CONFIG: Config = {
  introLines: [
    "Hey there",
    "Slow down for a second.",
    "I made something just for you.",
    "Ready?"
  ],
  questionTitle: "Will you be my Valentine?",
  subtext: "No pressure. Just a soft, real, honest “yes” if your heart says so.",
  yesMessageTitle: "Rik's First Valentines!!!",
  yesMessageBody: "I’d love to steal you this Valentine’s. Thank you for being you.",
  signature: "- Kaden",
  defaultAudioKey: 'awnw',
  audioTracks: {
    awnw: {
      src: "/assets/awnw.mp3",
      start: 12,
      end: null
    },
    pp: {
      src: "/assets/pp.mp3",
      start: 28,
      end: null
    },
    kmph: {
      src: "/assets/kmph.mp3",
      start: 55,
      end: 300
    }
  },
  emailMode: 'none', // Set to 'emailjs' and fill the below if you have an account
  emailjs: {
    publicKey: "YOUR_PUBLIC_KEY",
    serviceId: "YOUR_SERVICE_ID",
    templateId: "YOUR_TEMPLATE_ID"
  }

};

export const TEASING_MICROCOPY = [
  "Nice try :)",
  "Hmm… persistent.",
  "That button believes in survival.",
  "You’re really going for it.",
  "Careful… I might start smiling.",
  "Okay now this is getting cute.",
  "You don’t give up easily, do you?",
  "Confidence looks good on you.",
  "I respect the determination.",
  "Still trying? I like that.",
  "You’re making this interesting.",
  "At this point it's personal.",
  "I admire the commitment.",
  "Someone woke up bold today.",
  "This is kind of adorable.",
  "You’re not supposed to catch it.",
  "The universe is watching.",
  "Even fate is entertained.",
  "Plot twist: it keeps running.",
  "You vs destiny right now.",
  "This is becoming a love story.",
  "Okay hero, relax.",
  "You’re chasing pixels and feelings.",
  "This button is emotionally unavailable.",
  "Try again, I dare you.",
  "You’re enjoying this.",
  "I can tell.",
  "Still here?",
  "Good.",
  "Don’t stop now.",
  "You’re almost convincing me.",
  "Charm level increasing.",
  "Dangerously charming behavior.",
  "This is smooth.",
  "Suspiciously smooth.",
  "You planned this, didn’t you?",
  "I see the strategy.",
  "Bold strategy.",
  "Very bold.",
  "You’re winning points.",
  "Invisible points… but still.",
  "Okay now I'm impressed.",
  "You might actually deserve a yes.",
  "Confidence like that?",
  "Rare.",
  "Very rare.",
  "This energy… keep it.",
  "You’re kind of glowing right now.",
  "Not gonna lie.",
  "This is attractive behavior.",
  "Effort looks good on you.",
  "Real good.",
  "Still trying?",
  "I like that persistence.",
  "It says a lot about you.",
  "Good things, don’t worry.",
  "You’re doing great.",
  "Almost poetic.",
  "Rom-com main character energy.",
  "Yes… that energy.",
  "You’re making this hard to resist.",
  "Careful.",
  "I might say yes too easily.",
  "We don’t want that yet.",
  "Or do we?",
  "Okay now you're flirting.",
  "I can feel it.",
  "Smooth moves.",
  "Very smooth moves.",
  "You came prepared.",
  "I respect preparation.",
  "And intention.",
  "Mostly intention.",
  "You’re not leaving, huh?",
  "Good.",
  "Stay.",
  "Just a little longer.",
  "This moment’s kind of nice.",
  "You clicking.",
  "Me noticing.",
  "A whole story forming.",
  "Honestly?",
  "I’m smiling.",
  "Hope you are too.",
  "Because this is fun.",
  "Really fun.",
  "You’re making memories now.",
  "Tiny ones.",
  "But real.",
  "Okay… last warning.",
  "You’re getting closer.",
  "Dangerously closer.",
  "Heart might get involved.",
  "We don’t want accidents.",
  "Or maybe we do.",
  "You’re brave for this.",
  "And I like brave.",
  "Very much.",
  "At this point…",
  "you already know the answer.",
  "Just press yes.",
  "Come on.",
  "Don’t overthink it.",
  "You feel it too.",
  "I know you do.",
  "This is your moment.",
  "Make it count.",
  "Only one path today, love."
];

